services:
    nginx:
        image: nginx:stable-alpine
        container_name: test_task-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - test_task

    pgsql:
        image: 'postgres:15'
        container_name: test_task-pgsql
        restart: unless-stopped
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './data/database:/var/lib/postgresql/data'
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
        networks:
            - test_task

    php:
        container_name: test_task-php
        restart: unless-stopped
        build: docker/php
        volumes:
            - ./:/var/www/html
        networks:
            - test_task
        depends_on:
            - pgsql

networks:
    test_task:
        driver: bridge
